map_type: costmap

obstacle_range: 1.0 # 2.0 Sets the range (in meters) up to which obstacles are considered by the costmap
raytrace_range: 3.0 # 3.0 helps in determining the presence of obstacles even beyond the obstacle_range.

transform_tolerance: 0.2 # 0.0

robot_radius: 0.3 # 0.0 radius (in meters) of the robot
inflation_radius: 0.5 # 0.0This inflation helps the robot to maintain a safe distance from obstacles during navigation.
cost_scaling_factor: 3.0 #Higher values increase the cost and discourage the robot from passing close to obstacles.
map_type: costmap

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true}